version: '3'

services:
  database:
    # 使用镜像文件
    image: mysql
    # 容器名称
    container_name: mysql
    # 端口映射
    ports:
      - 3306:3306
    # 设置MySQL的root用户密码
    volumes:
      - ./mysql/lib/mysql:/var/lib/mysql
      - ./mysql/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345678'
